create table public.content_items (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  category text not null check (category in ('research', 'writing')),
  status text not null default 'draft' check (status in ('draft', 'published')),
  summary text not null default '',
  body text not null default '',
  venue text,
  year integer check (year is null or year between 1900 and 2200),
  publication_date date,
  featured boolean not null default false,
  external_url text,
  document_key text,
  document_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index content_items_public_listing_idx
  on public.content_items (status, category, featured desc, publication_date desc, year desc);

alter table public.content_items enable row level security;

create schema if not exists private;
revoke all on schema private from public;

create table private.site_owners (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table private.site_owners enable row level security;
revoke all on table private.site_owners from public, anon, authenticated;

create or replace function private.is_site_owner()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from private.site_owners
    where user_id = (select auth.uid())
  )
$$;

grant usage on schema public to anon, authenticated;
grant select on public.content_items to anon, authenticated;
grant insert, update, delete on public.content_items to authenticated;
grant usage, select on sequence public.content_items_id_seq to authenticated;
revoke all on function private.is_site_owner() from public;
grant usage on schema private to anon, authenticated;
grant execute on function private.is_site_owner() to anon, authenticated;

create policy "Published content is publicly readable"
on public.content_items for select to anon, authenticated
using (status = 'published' or private.is_site_owner());

create policy "Owner can create content"
on public.content_items for insert to authenticated
with check (private.is_site_owner());

create policy "Owner can update content"
on public.content_items for update to authenticated
using (private.is_site_owner()) with check (private.is_site_owner());

create policy "Owner can delete content"
on public.content_items for delete to authenticated
using (private.is_site_owner());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('documents', 'documents', false, 20971520, array['application/pdf']);

create policy "Published PDFs are readable"
on storage.objects for select to anon, authenticated
using (
  bucket_id = 'documents'
  and (
    private.is_site_owner()
    or exists (
      select 1 from public.content_items
      where content_items.document_key = storage.objects.name
        and content_items.status = 'published'
    )
  )
);

create policy "Owner can upload PDFs"
on storage.objects for insert to authenticated
with check (bucket_id = 'documents' and private.is_site_owner());

create policy "Owner can replace PDFs"
on storage.objects for update to authenticated
using (bucket_id = 'documents' and private.is_site_owner())
with check (bucket_id = 'documents' and private.is_site_owner());

create policy "Owner can delete PDFs"
on storage.objects for delete to authenticated
using (bucket_id = 'documents' and private.is_site_owner());
